### ISSUE TITLE
CI's cache key results in a single snapshot being created in first build and never updated

### ISSUE THREAD

**Issue by huonw** [pantsbuild/example-python#102]
We've been setting up our pants system and cribbing off this repo, so thanks for publishing it. However, we noticed that our CI was quickly getting much slower and discovered it was due to the use of a very simple cache key: `${{ runner.os }}-`.

It seems like if there's an exact match for a key, GitHub Actions will restore the cache, and _never_ update it even if the cached files changed during the run. The "Post Run" step for `actions/cache` says `Cache hit occurred on the primary key Linux-, not saving cache.`. This means that the first build with the cache will seed it, and all future builds will reuse that old one, and that cache will get less useful slowly (or not so slowly, in our case 😄 ) and builds longer.

We're experimenting with an alternative that incorporates progressively more detailed hashes:

- if the input code exactly matches, we'll get an exact cache hit
- otherwise, fallback to caches that are hopefully similar (firstly if only the code is different but pants.toml, lock files and BUILD files match, and then if only pants.toml and lock files match, and so on)

```yaml
      # FIXME: use a remote cache
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pants/setup
            ~/.cache/pants/lmdb_store
            ~/.cache/pants/named_caches
          key: >-
            pants-${{ hashFiles('pants.toml') }}-${{ hashFiles('3rdparty/**') }}-${{ hashFiles('**/BUILD') }}-${{ hashFiles('source/**') }}
          # if we don't have an exact match, search for a similar one (the hashes are vaguely
          # ordered from slowest to fastest changing, i.e. longer prefix match ≈ more sharing)
          restore-keys: |
            pants-${{ hashFiles('pants.toml') }}-${{ hashFiles('3rdparty/**') }}-${{ hashFiles('**/BUILD') }}-
            pants-${{ hashFiles('pants.toml') }}-${{ hashFiles('3rdparty/**') }}-
            pants-${{ hashFiles('pants.toml') }}-
            pants-
```

(This will result in... a lot of cache usage for a reasonably large project, but will be better than caches that are barely useful.)
