### ISSUE TITLE
Example using multiple Python versions on Github Actions

### ISSUE THREAD

**Issue by sureshjoshi** [pantsbuild/example-python#62]
Not a question, just leaving info for anyone who runs into this later (or, until pants supports Python 3.9/3.10). I have a project, where Pants requires python 3.7 or 3.8, most of my projects require python 3.9 - and one of the projects requires python 3.7 (because of where it's installed later).

Wasn't sure how to get Github Actions to handle this originally, but turns out it's very simple - just run setup-python twice in a row.

```yaml
name: Pex and Package

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Bootstrap Pants
        run: |
          ./pants --version

      - name: Create deployment package
        run: |
          ./pants package :mypackage

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: mypackage.tar.xz
          path: dist/*.xz

```
